# Create New Student Information Dictionary, convert to Pandas DataFrame
new_student = {
    "school": "GP",
    "sex": "M",
    "age": 17,
    "address": "U",
    "famsize": "LE3",
    "Pstatus": "T",
    "Medu": 4,
    "Fedu": 3,
    "Mjob": "teacher",
    "Fjob": "teacher",
    "reason": "course",
    "guardian": "mother",
    "traveltime": 3,
    "studytime": 2,
    "failures": 0,
    "schoolsup": "no",
    "famsup": "no",
    "paid": "no",
    "activities": "no",
    "nursery": "no",
    "higher": "no",
    "internet": "no",
    "romantic": "no",
    "famrel": 1,
    "freetime": 1,
    "goout": 1,
    "Dalc": 1,
    "Walc": 1,
    "health": 1,
    "absences": 1,
    "G1": 1,
    "G2": 1,
    "G3": 1,
}
